sudo: false

cache:
  directories:
    - $HOME/.gradle

language: java

jdk:
  - oraclejdk8

env:
  - TERM=dumb

before_install:
  - pip install --user codecov

install: true

before_script:
  - ./gradlew --version

script:
  - ./gradlew test jacocoTestReport coveralls

after_success:
  - codecov