sudo: false

cache:
  directories:
  - $HOME/.gradle

language: java

jdk:
- oraclejdk7
- oraclejdk8
- openjdk7

env:
- TERM=dumb

before_install:
  - pip install --user codecov

install: true

before_script:
  - ./gradlew --version

script:
  - ./gradlew test jacocoTestReport coveralls

after_success:
  - codecov